USE [master]
GO

CREATE LOGIN [crdopssbx\CRD-SQLSERVERADMIN-ADMIN-GS] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO

ALTER SERVER ROLE [SERVERADMIN]  ADD MEMBER [crdopssbx\CRD-SQLSERVERADMIN-ADMIN-GS]
GO

CREATE LOGIN [crdopssbx\CRD-SQLSETUPADMIN-ADMIN-GS] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO


ALTER SERVER ROLE [SETUPADMIN]  ADD MEMBER [crdopssbx\CRD-SQLSETUPADMIN-ADMIN-GS]
GO


CREATE LOGIN [crdopssbx\CRD-SQLSYSADMIN-ADMIN-GS] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO


ALTER SERVER ROLE [SYSADMIN]  ADD MEMBER [crdopssbx\CRD-SQLSYSADMIN-ADMIN-GS]
GO


CREATE LOGIN [crdopssbx\CRD-SQLSECURITYADMIN-ADMIN-GS] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO

ALTER SERVER ROLE [SECURITYADMIN]  ADD MEMBER [crdopssbx\CRD-SQLSECURITYADMIN-ADMIN-GS]
GO